inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-minitest
  - rubocop-performance
  - standard

inherit_from:
  - .rubocop/minitest.yml
  - .rubocop/strict.yml

inherit_gem:
  standard: config/base.yml
  syntax_tree: config/rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: <%= File.read(".tool-versions").split(/\s|-/)[1] %>
